resume: null
save_dir: ckpt/
log_dir: tensorboard/
gpu: false
n_gpu: null
metrics:
- _target_: srcs.model.metric.accuracy
- _target_: srcs.model.metric.precision
- _target_: srcs.model.metric.recall
- _target_: srcs.model.metric.f1
data_loader:
  _target_: srcs.data_loader.data_loaders.get_sign_dataloader
  csv_path_train: data/archive/train/train/train.csv
  csv_path_val: data/archive/train/validation/validation.csv
  batch_size: 32
  shuffle: true
  num_workers: 8
name: Conv3
arch:
  _target_: srcs.model.model.Conv3
  num_classes: 25
  dropout_rate: 0.5
loss:
  _target_: srcs.model.loss.nll_loss
optimizer:
  _target_: torch.optim.Adam
  lr: 0.001
  weight_decay: 0
  amsgrad: true
lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  step_size: 50
  gamma: 0.1
n_cpu: 8
batch_size: 32
learning_rate: 0.001
weight_decay: 0
scheduler_step_size: 50
scheduler_gamma: 0.1
status: train
trainer:
  epochs: 2
  logging_step: 100
  monitor: min loss/valid
  save_topk: 7
  early_stop: 10
  tensorboard: true
cwd: .
