# @package _global_
#name: LinearModel
name: Conv3
arch:
  #_target_: srcs.model.model.LinearModel
  _target_: srcs.model.model.Conv3
  num_classes: 25
  dropout_rate: 0.2
loss:
  _target_: srcs.model.loss.nll_loss
optimizer:
  _target_: torch.optim.Adam
  lr: ${learning_rate}
  weight_decay: ${weight_decay}
  amsgrad: true
lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  step_size: ${scheduler_step_size}
  gamma: ${scheduler_gamma}
